name: Build and deploy pre release packages on Merge to main

on:
    push:
        branches:
            - main

jobs:
    main:
        name: Main job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: setup git config and track main branch
              run: |
                  git config user.name "GitHub Cloud Actions Bot"
                  git config user.email "<srini.j135@gmail.com>"

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@inscriptors'
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: setup pnpm cache
              uses: actions/cache@v3
              with:
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: pnpm run build

            - name: lint packages
              run: pnpm run lint

            - name: Versioning main for Pre release
              run: |
                  git status
                  npx standard-version --prerelease alpha
